### ISSUE TITLE
是否可以检测 OpenID 的有效性?

### ISSUE THREAD

**Issue by Enter-tainer** [ManiaciaChao/yatm#2]
目前对于失效的 OpenID, 也会显示 "No signin avalible"

**Comment by Enter-tainer** [comment]
:thinking: 看起来 没有签到的时候, 和 openid 失效的时候, 返回的数据的长度都是 0

**Comment by ManiaciaChao** [comment]
有方法检测，失效`openId`拿不到用户信息（比如头像）。每隔几个请求检测下应该就可以。

**Comment by ManiaciaChao** [comment]
现在每 4 次获取签到信息，便会验证当前 `openId` 是否过期。https://github.com/ManiaciaChao/yatm/commit/85aca3cdb88254eda88600d5b204cd016c45def5
