### ISSUE TITLE
WIP: automatically re-acquire `openId` 

### ISSUE THREAD

**Issue by ManiaciaChao** [ManiaciaChao/yatm#3]
突然想到可以直接在本地起代理（比如小火箭或者圈x），从扫完二维码之后的页面就可以拿到`openId`。之后发到服务器或者代理网关什么的就好。
这样一来就可以接入 [sign-your-horse](https://github.com/naivekun/sign-your-horse) 或者容器化。
@MaxJ2000 @Enter-tainer

**Comment by MaxJ2000** [comment]
目前遇到的问题是代理的mitm只提供rewrite request/response的方法。然后如果yatm跑服务器上的话通知模块怎么处理

**Comment by ttyS0** [comment]
之前搓的一个脚本：https://gist.github.com/siger-young/c4a683f014de38dcb61086f72923883b

**Comment by ManiaciaChao** [comment]
> 目前遇到的问题是代理的mitm只提供rewrite request/response的方法。然后如果yatm跑服务器上的话通知模块怎么处理

通知很简单，推到tg或者wx上就行了：https://github.com/ManiaciaChao/yatm/projects/1#card-58758873

**Comment by ManiaciaChao** [comment]
related issue: https://github.com/naivekun/sign-your-horse/issues/1

**Comment by Enter-tainer** [comment]
> > 目前遇到的问题是代理的mitm只提供rewrite request/response的方法。然后如果yatm跑服务器上的话通知模块怎么处理
> 
> 通知很简单，推到tg或者wx上就行了：[ManiaciaChao/yatm/projects/1#card-58758873](https://github.com/ManiaciaChao/yatm/projects/1#card-58758873)

我自己写脚本的时候 推通知有用过 [telegram.sh](https://github.com/fabianonline/telegram.sh/blob/master/telegram), 可以参考
